### Example of product master data creation via Source system product messages
### SourceSystemProductMessages
@MessageId = {{$guid}}

@AOS = {{EnvAOS}}
@AOSToken = {{EnvAOSToken}}
@DataAreaId = {{EnvDataAreaId}}
@SourceSystem = {{EnvSourceSystem}}

@ItemNumber = NewItem06
@StorageDimensionGroupName = Ware
@TrackingDimensionGroupName = Owner
@InventoryReservationHierarchyName = DefOwner
@ItemModelGroupId = WOM
@ProductGroupId = WOM
@InventoryUnitSymbol = Pcs
@ProductGroupId = WOM
@UnitConversionSequenceGroupId = Pcs

POST {{AOS}}/data//SourceSystemProductMessages?cross-company=true
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

{
"SourceSystemId": "{{SourceSystem}}",
"MessageId": "{{MessageId}}",
"dataAreaId": "{{DataAreaId}}",
//"ProductSubtype": "{{ProductSubtype}}",
//"ProductDimensionGroupName": "{{ProductDimensionGroupName}}",
"SourceSystemProductNumber": "{{ItemNumber}}",
"SourceSystemItemNumber": "{{ItemNumber}}",
"SearchName": "",
"ProductSearchName": "",
"WarehouseMobileDeviceDescriptionLine1": "",
"WarehouseMobileDeviceDescriptionLine2": "",
"StorageDimensionGroupName": "{{StorageDimensionGroupName}}",
"TrackingDimensionGroupName": "{{TrackingDimensionGroupName}}",
"InventoryReservationHierarchyName": "{{InventoryReservationHierarchyName}}",
"ItemModelGroupId": "{{ItemModelGroupId}}",
"ProductGroupId": "{{ProductGroupId}}",
"InventoryUnitSymbol": "{{InventoryUnitSymbol}}",
"UnitConversionSequenceGroupId": "{{UnitConversionSequenceGroupId}}",
"PackSizeCategoryId": "",
"PackingMaterialGroupId": "",
"PackageClassId": "",
"ProductLifecycleStateId": "",
"PhysicalDimensionGroupId": "",
"InventoryCountingReasonCodePolicyName": "",
"ProductVolume": 0,
"GrossProductDepth": 0,
"TareProductWeight": 0,
"GrossProductWidth": 0,
"GrossProductHeight": 0,
"NetProductWeight": 0,
"FirstProductFilterGroupId": "",
"SecondProductFilterGroupId": "",
"FirstProductFilterCode": "",
"SecondProductFilterCode": "",
"ThirdProductFilterCode": "",
"FourthProductFilterCode": "",
"FifthProductFilterCode": "",
"SixthProductFilterCode": "",
"SeventhProductFilterCode": "",
"EighthProductFilterCode": "",
"NinthProductFilterCode": "",
"TenthProductFilterCode": "",
"UnitCost": 0,
"SerialNumberGroupCode": "",
"BatchNumberGroupCode": "",
"IsHazardousMaterial": "No",
"ShelfLifePeriodDays": 0,
"OriginCountryRegionId": "",
"ShelfAdvicePeriodDays": 0,
"BestBeforePeriodDays": 0
}