### Example for Inbound shipment order document attachment message

### MessageId
@MessageId = MSG-ISO-DA-000004
### OrderNumber
@OrderNumber = ISO-DA-000004
@AttachmentOrderHeaderNote = Note for order: {{OrderNumber}}

@AOS = {{EnvAOS}}
@AOSToken = {{$aadV2Token scopes:https://usnconeboxax1aos.cloud.onebox.dynamics.com/Odata.FullAccess tenantId:c83429a6-782b-4275-85cf-60ebe81250ee clientId:bf76fe84-c139-44e0-bd25-e3c83a753962}}
@DataAreaId = {{EnvDataAreaId}}
@Warehouse = {{EnvWarehouse}}
@SourceSystem = {{EnvSourceSystem}}

POST {{AOS}}/data/InboundShipmentOrderMessages
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

{
"MessageId": "{{MessageId}}",
"dataAreaId": "{{DataAreaId}}",
"SourceSystemId": "{{SourceSystem}}",
"OrderNumber": "{{OrderNumber}}",
"ReceivingWarehouseId": "{{Warehouse}}"
}

###

POST {{AOS}}/data/InboundShipmentOrderDocumentAttachmentMessages
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

{
  "MessageId": "{{MessageId}}",
  "dataAreaId": "{{DataAreaId}}",
  "SourceSystemId": "{{SourceSystem}}",
  "OrderNumber": "{{OrderNumber}}",
  "DocumentAttachmentTypeCode": "Note",
  "Notes": "{{AttachmentOrderHeaderNote}}"
}

###

POST {{AOS}}/data/InboundShipmentOrderLineMessages
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

{
"MessageId": "{{MessageId}}",
"dataAreaId": "{{DataAreaId}}",
"SourceSystemId": "{{SourceSystem}}",
"OrderNumber": "{{OrderNumber}}",
"OrderLineNumber": 1,
"ItemNumber": "A0001",
"ExpectedQuantity": 10,
"ExpectedUnitSymbol": "pcs"
}

###

POST {{AOS}}/data/InboundShipmentOrderMessages(dataAreaId='{{DataAreaId}}', SourceSystemId='{{SourceSystem}}', OrderNumber='{{OrderNumber}}', MessageId='{{MessageId}}')/Microsoft.Dynamics.DataEntities.Complete?cross-company=true
Authorization: Bearer {{AOSToken}}
Content-Type: application/json
 