### Outbound shipment order messages
### Outbound shipment order message with two lines

### MessageId
@MessageId = MSG-XD-OSO-000001
### OrderNumber
@OrderNumber = OSO-XD-000001
# X-docking-SourceID (will get line # added in this example)
@CrossDockSourceId = ISO-XD-000001
@ConsigneeName = Me
@ConsigneeCountryRegionId = USA
@RequestedShippingPeriodStart = 2023-11-17T08:00:00Z
@RequestedShippingPeriodEnd = 2023-11-17T08:00:00Z,

@AOS = {{EnvAOS}}
@AOSToken = {{$aadV2Token scopes:https://usnconeboxax1aos.cloud.onebox.dynamics.com/Odata.FullAccess tenantId:c83429a6-782b-4275-85cf-60ebe81250ee clientId:bf76fe84-c139-44e0-bd25-e3c83a753962}}
@DataAreaId = {{EnvDataAreaId}}
@Warehouse = {{EnvWarehouse}}
@SourceSystem = {{EnvSourceSystem}}

POST {{AOS}}/data/OutboundShipmentOrderMessages
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

{
"MessageId": "{{MessageId}}",
"dataAreaId": "{{DataAreaId}}",
"SourceSystemId": "{{SourceSystem}}",
"OrderNumber": "{{OrderNumber}}",
"ShipFromWarehouseId": "{{Warehouse}}",
"ConsigneeName": "{{ConsigneeName}}",
"ConsigneeCountryRegionId": "{{ConsigneeCountryRegionId}}",
"RequestedShippingPeriodStart": "{{RequestedShippingPeriodStart}}",
"RequestedShippingPeriodEnd": "{{RequestedShippingPeriodEnd}}"
}

###

POST {{AOS}}/data/OutboundShipmentOrderLineMessages
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

{
"MessageId": "{{MessageId}}",
"dataAreaId": "{{DataAreaId}}",
"SourceSystemId": "{{SourceSystem}}",
"OrderNumber": "{{OrderNumber}}",
"OrderLineNumber": 1,
"ItemNumber": "A0001",
"OrderedQuantity": 1,
"OrderedUnitSymbol": "Pcs"
}

###

POST {{AOS}}/data/OutboundShipmentOrderLineCrossDockMessages
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

{
"MessageId": "{{MessageId}}",
"dataAreaId": "{{DataAreaId}}",
"SourceSystemId": "{{SourceSystem}}",
"OrderNumber": "{{OrderNumber}}",
"OrderLineNumber": 1,
"CrossDockSourceId": "{{CrossDockSourceId}}-1",
"SourceLineRequestedQuantity": 1
}

###

POST {{AOS}}/data/OutboundShipmentOrderMessages(dataAreaId='{{DataAreaId}}', SourceSystemId='{{SourceSystem}}', OrderNumber='{{OrderNumber}}', MessageId='{{MessageId}}')/Microsoft.Dynamics.DataEntities.Complete?cross-company=true
Authorization: Bearer {{AOSToken}}
Content-Type: application/json
 