### Example of getting warehouse on-hand information related inventory on-hand report data for the report number provided via business event 'WHSSourceSystemInventoryOnhandReportBusinessEvent' 

@ReportNumber = cf444f2d-412e-49f5-b205-b58203240031
@Warehouse = {{EnvWarehouse}}

@AOS = {{EnvAOS}}
@AOSToken = {{EnvAOSToken}}
@ReportName = ERP

# All reports based on name
GET {{AOS}}/data/WarehouseInventoryOnhandReports?$filter=ReportName eq '{{ReportName}}'&cross-company=true
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

### Report based ReportNumber
GET {{AOS}}/data/WarehouseInventoryOnhandReports?$filter=ReportNumber eq ({{ReportNumber}})&cross-company=true
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

###

GET {{AOS}}/data/WarehouseInventoryOnhandReportLines?$filter=ReportNumber eq ({{ReportNumber}}) and OnHandQuantity ne 0 and WarehouseId eq '{{Warehouse}}'&cross-company=true
Authorization: Bearer {{AOSToken}}
Content-Type: application/json

